# Generated by Django 2.2 on 2019-03-04 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodfitnessApp', '0002_auto_20190304_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodfitnessmodel',
            name='password',
        ),
        migrations.AlterField(
            model_name='foodfitnessmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 19, 36, 2, 192855, tzinfo=utc)),
        ),
    ]
